---
title: "Exception Handling with Ron Burgundy"
author: "Mark LeBoeuf"
date: '2017-07-23T21:13:14-05:00'
summary: Exception handling is a critical component of any data science workflow.
  You write code. It breaks. You build logic to deal with the exceptions. Repeat. From
  my experience, one of point of confusion for new R users is how to handle exceptions,
  which is a bit more intuitive in Python. Accordingly, this post provides a practical
  overview of how to handle exceptions in R by first illustrating the concept in Python.
tags: ["R", "Python", "Exception Handling"]
categories: ["R", "Python", "Exception Handling"]
---



<div id="overview" class="section level3">
<h3>Overview</h3>
<p>Exception handling is a critical component of any data science workflow. You write code. It breaks. You create exceptions. Repeat. From my experience, a point of confusion for new R users is how to handle exceptions, which I believe is more intuitive in Python (at least initially). This post provides a practical overview of how to handle exceptions in R by first illustrating the concept in Python.</p>
</div>
<div id="exception-handling-in-python" class="section level3">
<h3>Exception Handling in Python</h3>
<p>I’ve listed some of my favorite Ron Burgundy vocal warm-up phrases below. As a side note, all are excellent for preparing your speaking voice before a big speech.</p>
<p><img src="error_handling_images/burgundy_1.jpg" width="500px" height="500px" /><img src="/Users/mlebo1/Desktop/site/content/post/error_handling_images/burgundy_2.jpg" width="500px" height="500px" /><img src="error_handling_images/burgundy_3.jpg" width="500px" height="500px" /><img src="error_handling_images/burgundy_4.jpg" width="500px" height="500px" /><img src="error_handling_images/burgundy_5.jpg" width="500px" height="500px" /></p>
<p>Let’s convert these into a list.</p>
<pre class="python"><code>strings = [&quot;how now brown cow&quot;, 
          &quot;a tarantula enjoys a fine piece of chewing gum&quot;, 
          &quot;the human torch was denied a bank loan&quot;,
          &quot;the arsonist has oddly shaped feet&quot;]</code></pre>
<p>Our goal is to extract the 5th element from each phrase. We’ll use a <code>list comprehension</code>, which maps or applies a function to each element in a list. The <code>extract_element</code> function below takes 3 arguments:</p>
<ul>
<li>strings - the string we want to split</li>
<li>split_character - the character we want to split our strings on (in this case a space “ “)</li>
<li>element_index - the index of the element we want to extract after splitting the string</li>
</ul>
<pre class="python"><code>def extract_element(strings, split_character, element_index):
  return(strings.split(split_character)[element_index])</code></pre>
<p>Here’s what we’ll get if we want only the first word:</p>
<pre class="python"><code>print([extract_element(x, &quot; &quot;, 0) for x in strings])</code></pre>
<pre class="python"><code>## [&#39;how&#39;, &#39;a&#39;, &#39;the&#39;, &#39;the&#39;]</code></pre>
<p>Great! Let’s extract the fifth word.</p>
<pre class="python"><code>print([extract_element(x, &quot; &quot;, 4) for x in strings])</code></pre>
<pre class="python"><code>## IndexError: list index out of range</code></pre>
<p>Uh oh. This error message indicates that we tried an index value that was out of range, which makes sense: “how now brown cow” only has 4 words. In order to address this issue, let’s add two keywords to our function – <code>try</code> and <code>except</code>. Just like it sounds, the function will first try to execute the top code block. If an exception occurs, the function will pass control to the bottom code block. Let’s update the above function with our new, exception-handling logic and try again.</p>
<pre class="python"><code>def extract_element_tc(strings, split_character, element_index):
    try:
        return(strings.split(split_character)[element_index])
    except IndexError:
        return(&quot;NO STRING HERE&quot;)
        
print([extract_element_tc(x, &quot; &quot;, 4) for x in strings])</code></pre>
<pre class="python"><code>## [&#39;NO STRING HERE&#39;, &#39;fine&#39;, &#39;denied&#39;, &#39;shaped&#39;]</code></pre>
<p>This time it worked without an issue. We simply said,“if there isn’t an element at this index, give me back a ‘NO STRING HERE’ label”. Now let’s achieve the same result in R.</p>
</div>
<div id="exception-handling-in-r" class="section level3">
<h3>Exception Handling in R</h3>
<p>As I mentioned in the intro, dealing with exceptions in R can be a bit tricky at first. Let’s set up the previous task in R.</p>
<pre class="r"><code>library(purrr)

strings = c(&quot;how now brown cow&quot;, 
          &quot;a tarantula enjoys a fine piece of chewing gum&quot;, 
          &quot;the human torch was denied a bank loan&quot;,
          &quot;the arsonist has oddly shaped feet&quot;)

extract_element = function(strings, split_character, element_index){
  string_out = purrr::map_chr(strsplit(strings, split_character),
                              element_index
                              )
  return(string_out)
}</code></pre>
<p>We’ll approach this via the <code>sapply</code> function, which maps or applies a function to each element of a list or vector. We’ll also wrap the output of <code>sapply</code> with the <code>unname</code> function, which converts our list into a vector by removing the labels associated with each parsed string.</p>
<pre class="r"><code>print(unname(sapply(strings, extract_element, &quot; &quot;, 1)))</code></pre>
<pre><code>## [1] &quot;how&quot; &quot;a&quot;   &quot;the&quot; &quot;the&quot;</code></pre>
<p>I think we know what happens next…</p>
<pre class="r"><code>print(unname(sapply(strings, extract_element, &quot; &quot;, 5)))</code></pre>
<pre class="r"><code>## Error: Result 1 is not a length 1 atomic vector </code></pre>
<p>Ok. So how do we replicate the <code>try-except</code> control flow in R? Via the <code>tryCatch</code> function. Let’s examine the complete function – <code>extract_element_tc</code> – in order to deal with the problem stated above.</p>
<pre class="r"><code>extract_element_tc = function(strings_vector, split_character, element_index){
  string_out = tryCatch({
    return(purrr::map_chr(strsplit(strings_vector, split_character), 
                          element_index
                          )
          )
  },
  error = function(cond){
    return(&quot;NO STRING HERE&quot;)
  })
}

print(unname(sapply(strings, extract_element_tc, &quot; &quot;, 5)))</code></pre>
<pre class="r"><code>## [1] &quot;NO STRING HERE&quot; &quot;fine&quot;           &quot;denied&quot;         &quot;shaped&quot; </code></pre>
<p>Boom. No errors this time. R is different in that tryCatch will have separate functions, referred to as handlers, that get called depending on the condition that occurs. In this case, we have 2 conditions– our desired condition, and the error condition. There are additional conditions that can be handled (see <a href="http://adv-r.had.co.nz/Exceptions-Debugging.html">here</a> for more detail). For example, you can also include a handler for <code>warnings</code> as well, which can be extremely helpful for finding exceptions that don’t break your code but instead give you undesired results.</p>
</div>
